import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import {
  CheckCircle2,
  Clock,
  Building2,
  SlidersHorizontal
} from 'lucide-react';

export const AlertsPage: React.FC = () => {
  const { alerts, approveAlert, dismissAlert } = useApp();
  const [filter, setFilter] = useState<'all' | 'HIGH' | 'MEDIUM' | 'LOW'>('all');

  const filteredAlerts = alerts.filter((a) => {
    if (filter === 'all') return true;
    return a.priority === filter;
  });

  const pendingCount = alerts.filter((a) => a.status === 'pending').length;

  return (
    <div className="space-y-6 pb-12 font-ui">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-3xl sm:text-4xl font-black font-display text-[#1A1A1A] tracking-tight">
              AI Alerts Inbox.
            </h1>
            <span className="px-3 py-0.5 rounded-full text-xs font-black uppercase tracking-wider bg-red-100 text-[#7A1F1F] border border-red-200">
              {pendingCount} Pending
            </span>
          </div>
          <p className="text-sm text-[#6E6E6E] mt-1 font-medium">
            Prioritized exception notifications and operational corrective actions generated by the AI engine.
          </p>
        </div>

        {/* Priority Filter Pills */}
        <div className="flex items-center gap-1.5 p-1 bg-white rounded-full border border-stone-200 text-xs font-bold font-ui">
          <button
            onClick={() => setFilter('all')}
            className={`px-3.5 py-1.5 rounded-full uppercase tracking-wider text-[11px] transition-all cursor-pointer ${
              filter === 'all'
                ? 'bg-[#5C3320] text-white '
                : 'text-[#6E6E6E] hover:text-[#1A1A1A]'
            }`}
          >
            All Alerts ({alerts.length})
          </button>
          <button
            onClick={() => setFilter('HIGH')}
            className={`px-3.5 py-1.5 rounded-full uppercase tracking-wider text-[11px] transition-all cursor-pointer ${
              filter === 'HIGH'
                ? 'bg-[#7A1F1F] text-white '
                : 'text-[#6E6E6E] hover:text-[#1A1A1A]'
            }`}
          >
            High Priority
          </button>
          <button
            onClick={() => setFilter('MEDIUM')}
            className={`px-3.5 py-1.5 rounded-full uppercase tracking-wider text-[11px] transition-all cursor-pointer ${
              filter === 'MEDIUM'
                ? 'bg-amber-600 text-white '
                : 'text-[#6E6E6E] hover:text-[#1A1A1A]'
            }`}
          >
            Medium
          </button>
          <button
            onClick={() => setFilter('LOW')}
            className={`px-3.5 py-1.5 rounded-full uppercase tracking-wider text-[11px] transition-all cursor-pointer ${
              filter === 'LOW'
                ? 'bg-blue-600 text-white '
                : 'text-[#6E6E6E] hover:text-[#1A1A1A]'
            }`}
          >
            Low
          </button>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-4">
        {filteredAlerts.length === 0 ? (
          <div className="p-12 text-center bg-white rounded-2xl border border-stone-200 text-stone-400 font-ui">
            <CheckCircle2 className="w-10 h-10 text-[#0E8A3E] mx-auto mb-2" />
            <h4 className="text-lg font-black font-display text-[#1A1A1A]">Inbox Zero.</h4>
            <p className="text-xs text-[#6E6E6E] mt-1">No alerts matching current filter criteria.</p>
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const isHigh = alert.priority === 'HIGH';
            const isMedium = alert.priority === 'MEDIUM';
            const isApproved = alert.status === 'approved';
            const isDismissed = alert.status === 'dismissed';

            return (
              <div
                key={alert.id}
                className={`p-6 rounded-2xl border transition-all font-ui ${
                  isApproved
                    ? 'bg-emerald-50/40 border-emerald-200 opacity-80'
                    : isDismissed
                    ? 'bg-stone-100 border-stone-200 opacity-60'
                    : isHigh
                    ? 'bg-white border-red-300 ring-1 ring-red-200'
                    : isMedium
                    ? 'bg-white border-amber-300 '
                    : 'bg-white border-stone-200 '
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                  <div className="space-y-2 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span
                        className={`text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-full ${
                          isHigh
                            ? 'bg-[#7A1F1F] text-white'
                            : isMedium
                            ? 'bg-amber-600 text-white'
                            : 'bg-blue-600 text-white'
                        }`}
                      >
                        {alert.priority} Priority
                      </span>

                      <span className="text-xs font-bold text-[#6E6E6E] flex items-center gap-1">
                        <Building2 className="w-3.5 h-3.5 text-stone-400" />
                        {alert.storeName}
                      </span>

                      <span className="text-xs text-stone-400 flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {alert.timestamp}
                      </span>

                      {isApproved && (
                        <span className="text-[10px] font-bold px-2.5 py-0.5 rounded-full bg-emerald-100 text-[#0E8A3E] flex items-center gap-1">
                          <CheckCircle2 className="w-3 h-3" /> Approved by Manager
                        </span>
                      )}

                      {isDismissed && (
                        <span className="text-[10px] font-bold px-2.5 py-0.5 rounded-full bg-stone-200 text-stone-700">
                          Dismissed
                        </span>
                      )}
                    </div>

                    <h3 className="text-lg font-black font-display text-[#1A1A1A]">{alert.title}.</h3>
                    <p className="text-xs text-[#6E6E6E] leading-relaxed">{alert.description}</p>

                    {/* Recommended Action Pill */}
                    <div className="p-3.5 bg-[#F5F4F1] rounded-xl border border-stone-200 text-xs mt-2">
                      <strong className="text-[#E85C1A] block mb-0.5 flex items-center gap-1.5 uppercase text-[10px] tracking-wider">
                        <SlidersHorizontal className="w-3.5 h-3.5" /> Recommended Corrective Action:
                      </strong>
                      <span className="text-[#1A1A1A] font-medium">{alert.recommendedAction}</span>
                      {alert.metricImpact && (
                        <div className="text-[11px] text-[#0E8A3E] font-bold mt-1">
                          Projected Value: {alert.metricImpact}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Action Buttons: Pill format */}
                  {!isApproved && !isDismissed && (
                    <div className="flex sm:flex-col gap-2 shrink-0 justify-center">
                      <button
                        onClick={() => approveAlert(alert.id)}
                        className="px-5 py-2.5 bg-[#E85C1A] hover:bg-[#D44D0F] text-white text-xs font-black uppercase tracking-wider rounded-full transition-all flex items-center justify-center gap-1.5 cursor-pointer"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5" /> Approve Action
                      </button>
                      <button
                        onClick={() => dismissAlert(alert.id)}
                        className="px-5 py-2 bg-white border border-stone-300 hover:bg-stone-50 text-[#6E6E6E] text-xs font-bold uppercase tracking-wider rounded-full transition-colors cursor-pointer"
                      >
                        Dismiss
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
